stages:
  data:
    cmd: python src/prepare_data.py
    deps:
    - src/prepare_data.py
    outs:
    - data/features.csv

  train_rf:
    cmd: python src/train_rf.py
    deps:
    - data/features.csv

  train_lr:
    cmd: python src/train_lr.py
    deps:
    - data/features.csv

  evaluate:
    cmd: python src/evaluate_models.py
    deps:
    - data/features.csv
    - models/model_RF.pkl
    - models/model_LR.pkl

metrics:
- reports/evaluate.json
artifacts:
  model_LR:
    path: models/model_LR.pkl
    type: model
    labels:
    - lr
    - example-rnd-monorepo
    - gen-2024
  model_RF:
    path: models/model_RF.pkl
    type: model
    labels:
    - rf
    - example-rnd-monorepo
    - gen-2024
  model_lr:
    path: models/model_lr.pkl
    type: model
    labels:
    - lr
    - example-rnd-monorepo
    - gen-2024
